swagger: "2.0"
info:
  version: "0.9.0"
  title: Jade POC App
# basePath prefixes all resource paths
basePath: /api/0.9.0
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /device:
    # binds a127 app logic to a route
    x-swagger-router-controller: device
    get:
      description: Returns devices info
      # used as the method name of the controller
      operationId: device_info
      parameters:
        - name: id
          in: query
          description: Device's ID
          required: false
          type: integer
        - name: type
          in: query
          description: Device's type
          required: false
          type: integer
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              # a pointer to a definition
              $ref: "#/definitions/Device"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /user:
    # binds a127 app logic to a route
    x-swagger-router-controller: user
    get:
      description: Returns user info
      # used as the method name of the controller
      operationId: user
      parameters:
        - name: id
          in: query
          description: User's ID
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              # a pointer to a definition
              $ref: "#/definitions/User"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

# complex objects have schema definitions
definitions:
  Device:
    required:
      - id
      - type
    properties:
      id:
        type: integer
      type:
        type: integer
      description:
        type: string
      ip:
        type: string
  User:
    required:
      - id
      - name
      - profile
    properties:
      id:
        type: string
      name:
        type: string
      profile:
        type: string
  ErrorResponse:
    required:
      - message
      - code
    properties:
      message:
        type: string
      code:
        type: integer
